---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
    owner: root
    group: root
    mode: '0744'
  with_items:
    - '/etc/logstash/conf.d/patterns'
    - '/etc/logstash/conf.d/templates'
    - '/etc/logstash/conf.d/databases'

- name: Copy pfELK Files
  copy: src={{ item.src }} dest={{ item.dest }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src 'files/patterns/pfelk.grok', dest: '/etc/logstash/conf.d/patterns/pfelk.grok'}
    - { src 'files/template/pf-geoip.json', dest: '/etc/logstash/conf.d/templates/pf-geoip.json'}
    - { src 'files/databases/pfelk.grok', dest: '/etc/logstash/conf.d/databases/rule-names.csv'}
    - { src 'files/databases/pfelk.grok', dest: '/etc/logstash/conf.d/databases/service-names-port-numbers.csv'}
    - { src 'files/01-inputs.conf', dest: '/etc/logstash/conf.d/01-inputs.conf'}
    - { src 'files/02-types.conf', dest: '/etc/logstash/conf.d/02-types.conf'}
    - { src 'files/03-filter.conf', dest: '/etc/logstash/conf.d/03-filter.conf'}
    - { src 'files/05-firewall.conf', dest: '/etc/logstash/conf.d/05-firewall.conf'}
    - { src 'files/10-others.conf', dest: '/etc/logstash/conf.d/10-others.conf'}
    - { src 'files/15-squid.conf', dest: '/etc/logstash/conf.d/15-squid.conf'}
    - { src 'files/20-suricata.conf', dest: '/etc/logstash/conf.d/20-suricata.conf'}
    - { src 'files/25-snort.conf', dest: '/etc/logstash/conf.d/25-snort.conf'}
    - { src 'files/30-geoip.conf', dest: '/etc/logstash/conf.d/30-geoip.conf'}
    - { src 'files/35-rules-desc.conf', dest: '/etc/logstash/conf.d/35-rules-desc.conf'}
    - { src 'files/36-ports-desc.conf', dest: '/etc/logstash/conf.d/36-ports-desc.conf'}
    - { src 'files/45-cleanup.conf', dest: '/etc/logstash/conf.d/45-cleanup.conf'}
    - { src 'files/50-outputs.conf', dest: '/etc/logstash/conf.d/50-outputs.conf'}

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
