---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
    owner: root
    group: root
    mode: '0744'
  with_items:
    - '/etc/logstash/conf.d/patterns'
    - '/etc/logstash/conf.d/templates'
    - '/etc/logstash/conf.d/databases'

- name: Copy pfELK Files
  copy: 
    src: "{{ item.src }}" 
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src 'files/patterns/pfelk.grok', /patterns/pfelk.grok'}
    - { src 'files/template/pf-geoip.json', /templates/pf-geoip.json'}
    - { src 'files/databases/pfelk.grok', /databases/rule-names.csv'}
    - { src 'files/databases/pfelk.grok', /databases/service-names-port-numbers.csv'}
    - { src '01-inputs.conf'}
    - { src '02-types.conf'}
    - { src '03-filter.conf'}
    - { src '05-firewall.conf'}
    - { src '10-others.conf'}
    - { src '15-squid.conf'}
    - { src '20-suricata.conf'}
    - { src '25-snort.conf'}
    - { src '30-geoip.conf'}
    - { src '35-rules-desc.conf'}
    - { src '36-ports-desc.conf'}
    - { src '45-cleanup.conf'}
    - { src '50-outputs.conf'}

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
