---

- name: Install openjdk repository
  become: yes
  block:
  - name: Add repository
    apt_repository:
      repo: ppa:openjdk-r/ppa
      state: present

- name: Update repositories cache and install "openjdk" package
  apt:
    name: openjdk-11-jdk
    update_cache: yes
