--- 

- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'gpg']
    state: present

- name: Add Elasticsearch repository key
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Add elasticsearch repository
  apt_repository:
    repo: "{{ es_apt_url }}"
    state: present

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Copy elasticsearch configuration
  copy:
    src: "../files/elasticsearch.yml"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: 0644
  notify: restart elasticsearch

- name: Install python pip
  apt:
    name: python-pip
    state: present

- name: Install python setuptools
  apt:
    name: python-setuptools
    state: present

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    daemon_reload: yes
    state: started
    enabled: yes
